# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: my_portfolio_development
  user: <%= ENV['PG_USER']%>
  password: <%= ENV['PG_PASSWORD']%>

test:
  <<: *default
  database: my_portfolio_test
  user: <%= ENV['PG_USER']%>
  password: <%= ENV['PG_PASSWORD']%>

production:
  <<: *default
  database: my_portfolio_production
  username: my_portfolio
  password: <%= ENV['MY_PORTFOLIO_DATABASE_PASSWORD'] %>
